<?php
date_default_timezone_set('Africa/Cairo');

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Language Handling
if (isset($_GET['lang'])) {
    $_SESSION['lang'] = $_GET['lang'];
}

if (!isset($_SESSION['lang'])) {
    $_SESSION['lang'] = 'ar';
}

$lang = $_SESSION['lang'];

// Translations
$translations = [
    'ar' => [
        'site_name' => 'ماركتيشن - صائد العملاء',
        'home' => 'الرئيسية',
        'login' => 'تسجيل الدخول',
        'register' => 'حساب جديد',
        'dashboard' => 'لوحة القيادة',
        'user_panel' => 'لوحة المستخدم',
        'admin_panel' => 'لوحة الإدارة',
        'logout' => 'تسجيل خروج',
        'hero_title' => 'استخرج عملاء فيسبوك بدقة عالية',
        'hero_subtitle' => 'استهدف العملاء المهتمين من صفحات المنافسين، الجروبات، والمنشورات، وقم بزيادة مبيعاتك فوراً.',
        'start_now' => 'ابدأ الاستخراج الآن',
        'view_pricing' => 'باقات الاشتراك',
        'footer_desc' => 'أقوى أداة لاستخراج واستهداف بيانات العملاء من فيسبوك.',
        'copyright' => 'جميع الحقوق محفوظة',

        // Modules
        'extraction_tools' => 'أدوات الاستخراج',
        'extract_pages' => 'استخراج من الصفحات',
        'extract_groups' => 'استخراج من الجروبات',
        'extract_posts' => 'استخراج من المنشورات',
        'my_tasks' => 'مهامي',
        'fb_accounts' => 'إدارة الصفحات',
        'manage_messages' => 'إدارة الرسائل',
        'add_account' => 'إضافة حساب',
        'total_leads' => 'إجمالي العملاء',
        'active_tasks' => 'مهام جارية',

        // Statuses
        'status_pending' => 'قيد الانتظار',
        'status_processing' => 'جاري العمل',
        'status_completed' => 'مكتمل',
        'status_failed' => 'فشل',

        // Common
        'welcome' => 'مرحباً',
        'profile' => 'الملف الشخصي',
        'settings' => 'الإعدادات',
        'overview' => 'نظرة عامة',
        'users' => 'المستخدمين',
        'manage_users' => 'إدارة المستخدمين',
        'active' => 'نشط',
        'inactive' => 'غير نشط',
        'edit' => 'تعديل',
        'delete' => 'حذف',
        'save' => 'حفظ',
        'saving_status' => 'جاري حفظ البيانات...',
        'saved_success' => 'تم الحفظ بنجاح',
        'save_settings' => 'حفظ الإعدادات',
        'update_settings' => 'تحديث الإعدادات',
        'saving_settings' => 'جاري حفظ الإعدادات...',
        'submit' => 'إرسال',
        'cancel' => 'إلغاء',
        'view' => 'عرض',
        'actions' => 'إجراءات',
        'download_csv' => 'تحميل CSV',
        'no_data' => 'لا توجد بيانات.',

        // Landing Page
        'features_title' => 'لماذا تستخدم أداتنا؟',
        'feature_1_title' => 'استهداف دقيق',
        'feature_1_desc' => 'نصل إلى المستخدمين المتفاعلين بالفعل مع صفحات ومناشير منافسيك.',
        'feature_2_title' => 'آمن ومحمي',
        'feature_2_desc' => 'نظام محاكاة ذكي لحماية حساباتك من الحظر أثناء عملية الاستخراج.',
        'feature_3_title' => 'تصدير فوري',
        'feature_3_desc' => 'حمل البيانات بصيغة Excel أو CSV واستخدمها في حملاتك الإعلانية فوراً.',

        'how_it_works_title' => 'خطوات العمل',
        'step_1_title' => 'أضف حساب فيسبوك',
        'step_1_desc' => 'اربط حسابك بأمان لنتمكن من الوصول للصفحات العامة.',
        'step_2_title' => 'حدد الهدف',
        'step_2_desc' => 'ضع رابط الصفحة، المنشور، أو الجروب المراد استهدافه.',
        'step_3_title' => 'استلم البيانات',
        'step_3_desc' => 'شاهد العداد وهو يجمع العملاء ثم حمل الملف النهائي.',

        'testimonials_title' => 'قصص نجاح',
        'testimonial_1' => 'أداة رائعة، ضاعفت مبيعاتي من خلال استهداف عملاء المنافسين.',
        'testimonial_1_author' => 'كريم محمود',
        'testimonial_2' => 'سهولة في الاستخدام ونتائج دقيقة جداً. أنصح بها.',
        'testimonial_2_author' => 'منى السيد',

        // Auth & Profile
        'email' => 'البريد الإلكتروني',
        'password' => 'كلمة المرور',
        'confirm_password' => 'تأكيد كلمة المرور',
        'personal_details' => 'البيانات الشخصية',
        'security' => 'الأمان',
        'save_changes' => 'حفظ التغييرات',

        // Extraction & Campaigns (New)
        'scan_inbox' => 'فحص الرسائل',
        'open_inbox' => 'فتح المراسلات',
        'synced_pages' => 'الصفحات المربوطة',
        'link_account' => 'ربط حساب جديد',
        'sync_pages' => 'مزامنة الصفحات',
        'campaigns' => 'الحملات الإعلانية',
        'create_campaign' => 'إنشاء حملة',
        'campaign_name' => 'اسم الحملة',
        'message_text' => 'نص الرسالة',
        'message_preview' => 'معاينة الرسالة',
        'image_url' => 'رابط الصورة (اختياري)',
        'target_leads' => 'العملاء المستهدفين',
        'interval' => 'الفاصل الزمني (ثواني)',
        'start' => 'بدء',
        'pause' => 'إيقاف مؤقت',
        'stop' => 'إيقاف نهائي',
        'sent' => 'تم الإرسال',
        'failed' => 'فشل',
        'pending' => 'قيد الانتظار',
        'progress' => 'التقدم',
        'select_all' => 'تحديد الكل',
        'clear_leads' => 'حذف البيانات',
        'total_found' => 'العدد المستخرج',
        'runner_title' => 'مشغل الحملة',
        'controls' => 'التحكم',
        'queue' => 'طابور الإرسال',
        'ready_msg' => 'جاهز للإطلاق...',
        'completed' => 'مكتمل!',
        'sending' => 'جاري الإرسال...',
        'paused' => 'متوقف مؤقتاً',
        'error_network' => 'خطأ في الشبكة',
        'confirm_delete' => 'هل أنت متأكد من الحذف؟',
        'confirm_stop' => 'هل أنت متأكد من إيقاف الحملة؟',
        'no_account_linked' => 'لا يوجد حسابات مربوطة بعد.',
        'no_pages_synced' => 'لا يوجد صفحات مزامنة',
        'access_token_help' => 'نحتاج توكن صالح للوصول للصفحات.',
        'current_password' => 'كلمة المرور الحالية',
        'new_password' => 'كلمة المرور الجديدة',
        'setup_campaign' => 'إعداد الحملات',
        'campaign_reports' => 'تقارير الحملات',
        'monitor_campaign' => 'متابعة / إدارة',
        'no_campaigns_found' => 'لا توجد حملات سابقة',
        'no_campaigns_found' => 'لا توجد حملات سابقة',
        'status_scheduled' => 'مجدولة',
        'status_running' => 'جارية',
        'view_report' => 'عرض التقرير',
        'export_csv' => 'تصدير CSV',
        'id' => 'المعرف',
        'page' => 'الصفحة',
        'delete_campaign' => 'حذف الحملة',
        'confirm_delete' => 'هل أنت متأكد من حذف هذه الحملة؟ لا يمكن التراجع.',
        'campaign_deleted' => 'تم حذف الحملة بنجاح.',
        'system_update' => 'تحديث النظام',
        'check_updates' => 'التحقق من التحديثات',
        'pull_code' => 'سحب الكود',
        'run_migrations' => 'تحديث قاعدة البيانات',
        'update_log' => 'سجل التحديث',
        'how_to_update' => 'كيفية التحديث',
        'current_version' => 'الإصدار الحالي',
        'latest_commit' => 'آخر تحديث',
        'check_github' => 'فحص GitHub',
        'update_from_github' => 'تحديث من GitHub',
        'update_database' => 'تحديث الهيكل',
        'backup_warning' => 'تنبيه: قم بعمل نسخة احتياطية قبل التحديث!',
        'step_1' => 'تحقق من وجود تحديثات جديدة',
        'step_2' => 'قم بتنزيل الكود الجديد',
        'step_3' => 'قم بتحديث قاعدة البيانات',
        'system_update_manager' => 'مدير تحديث النظام',
        'could_not_get_version' => 'تعذر الحصول على معلومات الإصدار.',
        'connection_failed' => 'فشل الاتصال.',
        'code_updated_success' => 'تم تحديث الكود بنجاح!',
        'failed_pull_updates' => 'فشل سحب التحديثات.',
        'no_migrations_found' => 'لم يتم العثور على مجلد التحديثات.',
        'migration_running' => 'جاري تشغيل:',
        'migration_completed' => 'اكتمل',
        'migration_failed' => 'فشل',
        'update_step_1_desc' => 'التحقق من وجود تغييرات جديدة في المستودع الرئيسي.',
        'update_step_2_desc' => 'تنزيل ودمج أحدث التغييرات بأمان إلى الخادم الخاص بك.',
        'update_step_3_desc' => 'تطبيق أي تغييرات ضرورية في قاعدة البيانات لضمان عمل النظام بسلاسة.',
        'backup_warning_msg' => 'يرجى التأكد من وجود نسخة احتياطية حديثة من قاعدة البيانات والملفات قبل المتابعة في أي تحديثات.',
        'git_error_detected' => 'لم يتم العثور على إعدادات Git.',
        'btn_fix_git' => 'تهيئة النظام (إصلاح Git)',
        'git_fix_success' => 'تم تهيئة Git وربط النظام بنجاح!',
        'git_fix_failed' => 'فشلت عملية التهيئة.',
        'troubleshooting' => 'استكشاف الأخطاء وإصلاحها',
        'force_git_init' => 'إعادة تهيئة الاتصال بـ GitHub',
        'force_git_desc' => 'هذه العملية قد تقوم باستبدال ملفاتك المحلية. يرجى التأكد من النسخ الاحتياطي.',
        'take_backup_now' => 'الذهاب لصفحة النسخ الاحتياطي (يوصى به)',
        'confirm_git_fix' => 'فهمت المخاطر، تابع الإصلاح',
        'no_leads_selected' => 'لم يتم اختيار عملاء',
        'please_select_leads_first' => 'يرجى اختيار العملاء المستهدفين من صندوق الوارد أولاً للبدء.',
        'go_to_inbox' => 'الذهاب للرسائل',
        'targeting' => 'الاستهداف',
        'selected_leads_from' => 'تم اختيار <span class="highlight text-indigo-400 font-bold mx-1">%d</span> عميل من صفحة <span class="highlight text-white font-bold mx-1">%s</span>',
        'scheduled_at' => 'وقت الإطلاق',
        'run_now' => 'تشغيل فوري الآن',
        'schedule_campaign' => 'جدولة الحملة',
        'start_immediately' => 'بدء التنفيذ فور الحفظ',
        'go_to_runner' => 'حفظ والذهاب للمشغل',
        'messenger_preview_hint' => 'هكذا ستظهر رسالتك على ماسنجر.',
        'preview_name_placeholder' => 'اسم العميل',
        'vars_hint' => 'المتغيرات المتاحة',
        'message_placeholder' => 'أهلاً {{name}}، كيف يمكنني مساعدتك؟',
        'image_url_placeholder' => 'https://example.com/image.jpg',
        'online_status' => 'متصل الآن',
        'customer_msg_sample' => 'مرحباً! أنا مهتم بخدماتكم.',
        'preview_empty_msg' => '(اكتب رسالتك لترى المعاينة هنا...)',
        'just_now' => 'الآن',
        'chars_unit' => 'حرف',
        'campaign_default_name' => 'حملة',
        'upload_image' => 'رفع صورة',
        'use_url' => 'رابط مباشر',
        'local_file' => 'ملف محلي',
        'campaign_not_found' => 'الحملة غير موجودة.',
        'campaign_label' => 'الحملة:',
        'empty_queue_title' => 'طابور الإرسال فارغ أو مكتمل.',
        'empty_queue_desc' => 'حاول فحص الصفحة مجدداً إذا كان هذا غير متوقع.',
        'checking_token' => 'جاري فحص رمز الوصول...',
        'token_invalid' => 'رمز الوصول منتهي أو غير صالح',
        'conn_error' => 'خطأ في الاتصال أثناء فحص الرمز.',
        'sending_batch' => 'جاري إرسال الدفعة...',
        'waiting' => 'انتظار',
        'confirm_stop_campaign' => 'إيقاف العملية الحالية والعودة للخلف؟',
        'enter_valid_token' => 'يرجى إدخال رمز صالح',
        'updating_btn' => 'جاري التحديث...',
        'update_token_error' => 'خطأ أثناء تحديث الرمز.',
        'campaign_finished_title' => '🎉 انتهت الحملة بنجاح',
        'rerun_campaign' => 'إعادة تشغيل الحملة',
        'status_sending_small' => 'جاري الإرسال',
        'status_sent_small' => 'تم الإرسال',
        'status_failed_small' => 'فشل',
        'status_pending_small' => 'في الانتظار',
        'service_error' => 'خطأ في الاتصال بخدمة الإرسال.',
        'export_error' => 'فشل إنشاء الصورة. يرجى محاولة أخذ لقطة شاشة.',
        'lead_info' => 'بيانات العميل',
        'queue_list' => 'قائمة الانتظار',
        'campaign_progress' => 'تقدم الحملة',
        'estimated_time' => 'الوقت المتبقي المتوقع',
        'finished_status' => 'مكتمل',
        'retry_count_label' => 'مرات إعادة المحاولة',
        'retry_delay_label' => 'فاصل الإعادة (ثواني)',
        'retrying_status' => 'إعادة محاولة (%d/%d)',
        'starts_in' => 'يبدأ خلال:',


        // Contact
        'contact_us' => 'اتصل بنا',
        'contact_subtitle' => 'لديك استفسار؟ فريقنا جاهز للرد عليك في أسرع وقت ممكن.',
        'send_message' => 'إرسال رسالة',
        'your_name' => 'الاسم الكامل',
        'your_message' => 'نص الرسالة',
        'subject' => 'الموضوع',
        'phone' => 'رقم الهاتف',
        'msg_success' => 'تم إرسال رسالتك بنجاح! سنقوم بالرد عليك قريباً.',
        'search_placeholder' => 'ابحث بالاسم أو المعرف (ID)...',
        'token_expired_title' => 'انتهت صلاحية الجلسة!',
        'token_expired_msg' => 'عذراً، يبدو أن صلاحية رمز الوصول (Access Token) قد انتهت. لا تقلق، يمكنك تحديثه هنا والاستمرار من حيث توقفت.',
        'new_token_placeholder' => 'أدخل رمز الوصول الجديد (Page Access Token)...',
        'update_token_btn' => 'تحديث الرمز والاستمرار',
        'token_updated_success' => 'تم تحديث الرمز بنجاح! يمكنك الآن إكمال الحملة.',
        'report_title' => 'تقرير ملخص الحملة',
        'report_success' => 'إرسال ناجح',
        'report_failed' => 'فشل الإرسال',
        'report_delivered' => 'تم التسليم بنجاح',
        'report_needs_re_routing' => 'تحتاج إعادة توجيه',
        'report_total_recipients' => 'إجمالي المستقبلين',
        'report_date_logged' => 'تاريخ التقرير',
        'report_powered_by' => 'مدعوم بمحرك MARKETATION',
        'report_save_image' => 'حفظ كصورة (.PNG)',
        'report_close' => 'إغلاق التقرير',
        'report_people' => 'أشخاص',
        'generating_image' => 'جاري إنشاء الصورة...',

        // Footer & Misc
        'about_us' => 'من نحن',
        'about_subtitle' => 'شريكك الذكي في عالم التسويق الرقمي',
        'about_desc' => 'نحن نقدم أقوى الحلول التقنية لاستخراج بيانات العملاء المهتمين من فيسبوك. هدفنا هو مساعدة الشركات والمسوقين على الوصول إلى جمهورهم المستهدف بدقة واحترافية عالية، مع ضمان أعلى مستويات الأمان والسرعة في العمل.',
        'about_subtitle_ar' => 'عنوان من نحن الفرعي (عربي)',
        'about_subtitle_en' => 'عنوان من نحن الفرعي (إنجليزي)',
        'about_btn_ar' => 'نص زر من نحن (عربي)',
        'about_btn_en' => 'نص زر من نحن (إنجليزي)',
        'about_btn' => 'نص زر من نحن',
        'terms_service' => 'شروط الخدمة',
        'privacy_policy' => 'سياسة الخصوصية',
        'follow_us' => 'تابعنا',
        'hero_badge' => 'الأداة رقم #1 للتسويق',
        'hero_feature' => 'دقة تصل إلى 99% في استخراج بيانات العملاء المهتمين فعلياً.',
        'fast_secure' => 'سريع وآمن',
        'happy_users' => '+5000 مسوق',

        // Notifs
        'notifications' => 'الإشعارات',
        'mark_all_read' => 'تحديد الكل كمقروء',
        'view_all' => 'عرض الكل',
        'no_notifications' => 'لا توجد إشعارات',
        'unread_notifications' => 'إشعارات غير مقروءة',
        'api_status' => 'حالة الاتصال',
        'connected' => 'متصل',
        'not_connected' => 'غير متصل',
        'manage_profiles' => 'إدارة الحسابات الشخصية',
        // Facebook Accounts (User Section)
        'link_new_account' => 'ربط حساب جديد',
        'account_name_label' => 'اسم الحساب (للتمييز)',
        'account_name_placeholder' => 'مثلاً: حسابي الشخصي',
        'fb_id_label' => 'معرف فيسبوك (اختياري)',
        'fb_id_placeholder' => '123456789',
        'access_token_label' => 'رمز الوصول (Access Token)',
        'access_token_placeholder' => 'ضع الرمز هنا (EAAB...)',
        'access_token_note' => 'نحتاج لرمز صالح لاستيراد الصفحات والمحتوى.',
        'btn_link_account' => 'ربط الحساب الآن',
        'your_linked_accounts' => 'حساباتك المربوطة',
        'btn_sync_pages' => 'مزامنة الصفحات',
        'confirm_delete_account' => 'هل أنت متأكد؟ سيتم حذف كافة البيانات المرتبطة بهذا الحساب.',
        'synced_pages_title' => 'الصفحات المزامنة',
        'synced_pages_subtitle' => 'الصفحات التي تم جلبها من حساباتك. اختر صفحة لفتح صندوق الوارد.',
        'page_info' => 'بيانات الصفحة',
        'category' => 'الفئة',
        'no_accounts_linked' => 'لا يوجد حسابات مربوطة بعد. أضف حساباً للبدء.',
        'no_pages_synced_desc' => 'لم يتم مزامنة أي صفحات. اضغط على "مزامنة الصفحات" في أحد الحسابات أعلاه.',
        'msg_account_linked' => 'تم ربط الحساب بنجاح!',
        'msg_sync_success' => 'تمت مزامنة %d صفحة بنجاح!',
        'msg_no_pages' => 'لم يتم العثور على صفحات لهذا الحساب.',

        // Support
        'support_tickets' => 'الدعم الفني',
        'create_ticket' => 'تذكرة جديدة',
        'status' => 'الحالة',
        'last_update' => 'آخر تحديث',
        'open' => 'مفتوحة',
        'closed' => 'مغلقة',
        'answered' => 'تم الرد',
        'solved' => 'تم الحل',
        'arabic' => 'عربي',
        'english' => 'إنجليزي',

        // Misc
        'notifications_muted_msg' => 'تم كتم الإشعارات',
        'unmute_notifications' => 'إلغاء كتم الإشعارات',
        'mute_notifications' => 'كتم الإشعارات',
        'mark_read' => 'تحديد كمقروء',
        'view_all_notifications' => 'عرض كل الإشعارات',
        'features' => 'المميزات',
        'faqs' => 'الأسئلة الشائعة',
        'testimonials' => 'آراء العملاء',
        'contact' => 'تواصل معنا',
        'how_it_works' => 'كيف يعمل؟',
        'backup_restore' => 'النسخ الاحتياطي',
        'close_menu' => 'إغلاق القائمة',
        'stat_users' => 'مستخدم نشط',
        'stat_leads' => 'عميل مستخرج',
        'stat_satisfaction' => 'نسبة الرضا',
        'stat_support' => 'دعم فني',
        'cta_title' => 'جاهز لتنمية أعمالك؟',
        'cta_subtitle' => 'ابدأ باستخراج بيانات العملاء اليوم واترك منافسيك خلفك.',
        'cta_button' => 'إنشاء حساب مجاني',
        'sim_title' => 'محاكي الأرباح',
        'sim_desc' => 'توقع نتائج حملتك التسويقية',
        'sim_followers' => 'عدد متابعي الهدف',
        'sim_engagement' => 'نسبة التفاعل المتوقعة',
        'sim_total_leads' => 'إجمالي العملاء المستهدفين',
        'sim_accuracy' => 'دقة استخراج عالية',
        'sim_btn' => 'ابدأ الاستخراج الآن',
        'settings_updated' => 'تم تحديث الإعدادات بنجاح!',
        'site_info' => 'معلومات الموقع',
        'hero_section' => 'قسم الهيرو',
        'about_section' => 'قسم من نحن',
        'contact_info_settings' => 'إعدادات التواصل',
        'smtp_settings' => 'إعدادات البريد (SMTP)',
        'notification_settings' => 'إعدادات الإشعارات',
        'site_logo' => 'شعار الموقع',
        'site_favicon' => 'أيقونة الموقع (Favicon)',
        'site_name_ar' => 'اسم الموقع (عربي)',
        'site_name_en' => 'اسم الموقع (إنجليزي)',
        'footer_description_ar' => 'وصف التذييل (عربي)',
        'footer_description_en' => 'وصف التذييل (إنجليزي)',
        'contact_form_email' => 'بريد استقبال الرسائل',
        'maintenance_mode' => 'وضع الصيانة',
        'off_live' => 'متوقف (الموقع يعمل)',
        'on_maintenance' => 'مفعل (وضع الصيانة)',
        'enable_scroll_top' => 'تفعيل زر الصعود للأعلى',
        'hero_title_ar' => 'عنوان الهيرو (عربي)',
        'hero_feature_ar' => 'مميزة الهيرو (عربي)',
        'hero_subtitle_ar' => 'العنوان الفرعي للهيرو (عربي)',
        'hero_title_en' => 'عنوان الهيرو (إنجليزي)',
        'hero_feature_en' => 'مميزة الهيرو (إنجليزي)',
        'hero_subtitle_en' => 'العنوان الفرعي للهيرو (إنجليزي)',
        'about_title_ar' => 'عنوان من نحن (عربي)',
        'about_desc_ar' => 'وصف من نحن (عربي)',
        'mission_ar' => 'المهمة (عربي)',
        'vision_ar' => 'الرؤية (عربي)',
        'about_title_en' => 'عنوان من نحن (إنجليزي)',
        'about_desc_en' => 'وصف من نحن (إنجليزي)',
        'mission_en' => 'المهمة (إنجليزي)',
        'vision_en' => 'الرؤية (إنجليزي)',
        'social_links' => 'روابط التواصل الاجتماعي',
        'smtp_configuration' => 'إعدادات خادم البريد',
        'smtp_host' => 'مضيف SMTP',
        'smtp_port' => 'منفذ SMTP',
        'smtp_encryption' => 'التشفير',
        'smtp_username' => 'اسم مستخدم SMTP',
        'smtp_password' => 'كلمة مرور SMTP',
        'smtp_from_name' => 'اسم المرسل',
        'smtp_info_note' => 'تأكد من صحة إعدادات SMTP لضمان وصول رسائل البريد الإلكتروني للمستخدمين.',
        'email_notifications_control' => 'التحكم في إشعارات البريد',
        'registration_events' => 'أحداث التسجيل',
        'notify_admin_new_user' => 'تنبيه الإدمن عند تسجيل مستخدم جديد',
        'notify_admin_new_user_desc' => 'إرسال بريد إلكتروني للإدارة عند إنشاء حساب جديد.',
        'notify_client_welcome' => 'إرسال رسالة ترحيب للمستخدم',
        'notify_client_welcome_desc' => 'إرسال بريد ترحيبي للمستخدم بعد التسجيل.',
        'exchange_events' => 'أحداث الطلبات',
        'notify_admin_new_order' => 'تنبيه الإدمن عند طلب جديد',
        'notify_admin_new_order_desc' => 'إرسال تنبيه للإدارة عند بدء عملية استخراج جديدة.',
        'notify_client_new_order' => 'تنبيه المستخدم عند بدء الطلب',
        'notify_client_new_order_desc' => 'إرسال تأكيد للمستخدم عند بدء عملية الاستخراج.',
        'notify_client_status_change' => 'تنبيه بتغير حالة الطلب',
        'notify_client_status_change_desc' => 'إرسال بريد للمستخدم عند اكتمال أو فشل المهمة.',
        'security_note' => 'ملاحظة أمنية',
        'forgot_password_always_active' => 'نظام استعادة كلمة المرور يعمل دائماً ولا يتأثر بهذه الإعدادات.',
        'maintenance_placeholder' => 'الموقع تحت الصيانة حالياً، سنعود قريباً...',
        'landing_content' => 'إدارة محتوى الصفحة',
        'features_section' => 'قسم المميزات',
        'steps_section' => 'قسم خطوات العمل',
        'stats_section' => 'قسم العدادات',
        'cta_section' => 'قسم دعوة العمل (CTA)',
        'about_image' => 'صورة قسم من نحن',
        'stat_value' => 'القيمة الرقمية',
        'feature' => 'الميزة',
        'step' => 'الخطوة',
        'icon' => 'الأيقونة',
        'choose_icon' => 'اختر الأيقونة',
        'features_title_ar' => 'عنوان قسم المميزات (عربي)',
        'features_title_en' => 'عنوان قسم المميزات (إنجليزي)',
        'how_it_works_title_ar' => 'عنوان قسم خطوات العمل (عربي)',
        'how_it_works_title_en' => 'عنوان قسم خطوات العمل (إنجليزي)',
        'testimonials_title_ar' => 'عنوان قسم آراء العملاء (عربي)',
        'testimonials_title_en' => 'عنوان قسم آراء العملاء (إنجليزي)',
        'faqs_title_ar' => 'عنوان قسم الأسئلة الشائعة (عربي)',
        'faqs_title_en' => 'عنوان قسم الأسئلة الشائعة (إنجليزي)',
        'facebook' => 'فيسبوك',
        'twitter' => 'تويتر (X)',
        'instagram' => 'إنستقرام',
        'telegram' => 'تيليجرام',
        'whatsapp' => 'واتساب',
        'youtube' => 'يوتيوب',
        'linkedin' => 'لينكد إن',
        'tiktok' => 'تيك توك',
        'contact_phone' => 'رقم هاتف التواصل',
        'contact_address_ar' => 'العنوان (عربي)',
        'contact_address_en' => 'العنوان (إنجليزي)',
        'services_section' => 'قسم خدماتنا',
        'services_title_ar' => 'عنوان قسم الخدمات (عربي)',
        'services_title_en' => 'عنوان قسم الخدمات (إنجليزي)',
        'service' => 'الخدمة',
        'service_title' => 'عنوان الخدمة',
        'service_desc' => 'وصف الخدمة (كل سطر يعد ميزة)',
        'service_btn_ar' => 'نص زر الخدمة (عربي)',
        'service_btn_en' => 'نص زر الخدمة (إنجليزي)',
        'most_popular' => 'الأكثر شعبية',
        'featured_service' => 'خدمة مميزة',
        'testimonial' => 'رأي عميل',
        'testimonial_content' => 'نص الرأي',
        'testimonial_author' => 'اسم العميل',
        'testimonial_image' => 'صورة العميل',
        'faq' => 'سؤال شائع',
        'faq_question' => 'السؤال',
        'faq_answer' => 'الإجابة',
        'contact_info' => 'معلومات التواصل',
        'contact_email' => 'البريد الإلكتروني للتواصل',
        'test_smtp_settings' => 'اختبار إعدادات SMTP',
        'test_email_address' => 'البريد الإلكتروني للتجربة',
        'send_test_email' => 'إرسال رسالة تجربة',
        'smtp_test_failed' => 'فشل إرسال رسالة التجربة. يرجى التحقق من الإعدادات.',
        'msg_account_deleted' => 'تم حذف الحساب بنجاح',
        'msg_rate_limit_error' => 'عفواً، تم تجاوز الحد المسموح به من الطلبات مؤقتاً (Rate Limit). يرجى الانتظار بضع دقائق ثم المحاولة مرة أخرى.',
        'fb_accounts_desc' => 'إدارة وتحكم في حسابات فيسبوك والصلاحيات الممنوحة',

        // Inbox Page
        'inbox_page_title' => 'مراسلات الصفحة',
        'page_id_label' => 'معرف الصفحة:',
        'last_updated' => 'آخر تحديث:',
        'never_updated' => 'أبداً',
        'total_audience' => 'إجمالي الجمهور',
        'inbox_leads' => 'عملاء الرسائل',
        'scan_limit' => 'عدد المحادثات',
        'chats_label' => 'محادثة',
        'clear_database' => 'مسح البيانات',
        'clear_confirm' => 'هل أنت متأكد من مسح جميع العملاء من قاعدة البيانات؟',
        'user_identity' => 'هوية المستخدم',
        'psid_label' => 'PSID (معرف خاص)',
        'interaction_date' => 'تاريخ التفاعل',
        'fb_user_role' => 'مستخدم فيسبوك',
        'no_leads_found' => 'لم يتم العثور على عملاء بعد',
        'click_scan_hint' => 'اضغط "فحص الرسائل" لجلب أحدث المحادثات.',
        'scan_success' => 'تم فحص الرسائل بنجاح! تمت معالجة %d محادثة.',
        'scan_no_results' => 'لم يتم العثور على محادثات جديدة في صندوق الوارد.',
        'leads_cleared' => 'تم مسح بيانات العملاء بنجاح.',
        'page_not_found' => 'الصفحة غير موجودة أو ليس لديك صلاحية الوصول.',
        'scan_delay_label' => 'فاصل زمني (ثواني)',
        'scan_delay_hint' => 'الانتظار بين الطلبات لتجنب الحظر',
        'extract_mode_label' => 'نوع الاستخراج',
        'extract_all_option' => 'استخراج الكل',
        'extract_limit_option' => 'عدد محدد',
        'btn_start' => 'بدء الحملة',
        'btn_pause' => 'إيقاف مؤقت',
        'btn_resume' => 'استكمال',
        'btn_stop' => 'إيقاف نهائي',
        'status_ready' => 'جاهز للبدء...',
        'status_scanning' => 'جاري الفحص... (تم جلب %s)',
        'status_paused' => 'تم الإيقاف مؤقتاً',
        'status_finished' => 'اكتملت العملية!',
        'lbl_delay' => 'تأخير',
        'lbl_limit' => 'الحد الأقصى',
        'lbl_batch_size' => 'حجم الدفعة',
        'lbl_total_goal' => 'الاجمالي المطلوب',
        'lbl_seconds' => 'ثانية',
        'cron_manager_title' => 'مدير المهام التلقائي',
        'auto_cron_title' => 'التشغيل الذاتي (بدون تدخل)',
        'auto_cron_desc' => 'عند تفعيل هذا الخيار، سيقوم النظام بتشغيل نفسه تلقائياً في الخلفية حتى لو أغلقت الموقع. يستخدم هذا الخيار تقنية (Self-Looping) لضمان استمرار الحملات.',
        'start_auto_loop' => 'تفعيل التشغيل التلقائي',
        'stop_auto_loop' => 'إيقاف التشغيل التلقائي',
        'loop_enabled' => 'تم تفعيل التشغيل التلقائي بنجاح. الحملات ستعمل الآن في الخلفية.',
        'loop_disabled' => 'تم إيقاف التشغيل التلقائي.',
        'system_running_background' => 'النظام يعمل في الخلفية حالياً...',
        'manual_cron_title' => 'إعداد Cron Job (للاستضافة)',
        'manual_cron_desc' => 'إذا كنت تفضل الإعداد اليدوي عبر cPanel، انسخ هذا الأمر وضعه ليعمل كل دقيقة:',
        'click_to_copy' => 'اضغط للنسخ',

        'status_processed' => 'تم معالجة %s عميل...',
        'status_sleeping' => 'انتظار %s ثانية...',
        'status_sleeping' => 'انتظار %s ثانية...',
        'save_failed' => 'فشل الحفظ',
        'save_failed_network' => 'خطأ في الشبكة',
        'batch_size' => 'حجم الدفعة (رسائل)',
        'unit_s' => 'ث',
        'unit_msg' => 'رسالة',
        'lbl_retry_delay' => 'تأخير المحاولة',
        'lbl_retry_count' => 'عدد المحاولات',
    ],
    'en' => [
        'site_name' => 'Marketation Extractor',
        'home' => 'Home',
        'login' => 'Login',
        'register' => 'Register',
        'dashboard' => 'Dashboard',
        'user_panel' => 'User Panel',
        'admin_panel' => 'Admin Panel',
        'logout' => 'Logout',
        'hero_title' => 'Extract High Quality FB Leads',
        'hero_subtitle' => 'Target interested customers from competitor pages, groups, and posts to boost sales instantly.',
        'start_now' => 'Start Extraction',
        'view_pricing' => 'Pricing',
        'footer_desc' => 'The most powerful tool for extracting and targeting customer data from Facebook.',
        'copyright' => 'All Rights Reserved',

        // Modules
        'extraction_tools' => 'Extraction Tools',
        'extract_pages' => 'Page Extraction',
        'extract_groups' => 'Group Extraction',
        'extract_posts' => 'Post Extraction',
        'my_tasks' => 'My Tasks',
        'fb_accounts' => 'Page Management',
        'manage_messages' => 'Message Management',
        'add_account' => 'Add Account',
        'total_leads' => 'Total Leads',
        'active_tasks' => 'Active Tasks',

        // Statuses
        'status_pending' => 'Pending',
        'status_processing' => 'Processing',
        'status_completed' => 'Completed',
        'status_failed' => 'Failed',

        // Common
        'welcome' => 'Welcome',
        'profile' => 'Profile',
        'settings' => 'Settings',
        'overview' => 'Overview',
        'users' => 'Users',
        'manage_users' => 'Manage Users',
        'active' => 'Active',
        'inactive' => 'Inactive',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'save' => 'Save',
        'submit' => 'Submit',
        'cancel' => 'Cancel',
        'view' => 'View',
        'actions' => 'Actions',
        'download_csv' => 'Download CSV',
        'no_data' => 'No data found.',

        // Landing Page
        'features_title' => 'Why Choose Us?',
        'feature_1_title' => 'Precise Targeting',
        'feature_1_desc' => 'Reach users who are actually interacting with your competitors.',
        'feature_2_title' => 'Safe & Secure',
        'feature_2_desc' => 'Smart simulation technology to keep your accounts safe from bans.',
        'feature_3_title' => 'Instant Export',
        'feature_3_desc' => 'Download data as Excel or CSV and use it in your campaigns immediately.',

        'how_it_works_title' => 'How It Works',
        'step_1_title' => 'Add Facebook Account',
        'step_1_desc' => 'Link your account securely to access public page data.',
        'step_2_title' => 'Select Target',
        'step_2_desc' => 'Enter the URL of the Page, Post, or Group you want to target.',
        'step_3_title' => 'Get Data',
        'step_3_desc' => 'Watch the counter gently leads, then download the final file.',

        'testimonials_title' => 'Success Stories',
        'testimonial_1' => 'Great tool, doubled my sales by targeting competitor leads.',
        'testimonial_1_author' => 'Karim Mahmoud',
        'testimonial_2' => 'Easy to use and very accurate results. Highly recommended.',
        'testimonial_2_author' => 'Mona El-Sayed',

        // Auth & Profile
        'email' => 'Email',
        'password' => 'Password',
        'confirm_password' => 'Confirm Password',
        'personal_details' => 'Personal Details',
        'security' => 'Security',
        'save_changes' => 'Save Changes',
        'current_password' => 'Current Password',
        'new_password' => 'New Password',
        'setup_campaign' => 'Setup Campaign',
        'campaign_report' => 'Campaign Report',
        'status_stopped' => 'Stopped',

        'system_update' => 'System Update',
        'check_updates' => 'Check Updates',
        'pull_code' => 'Pull Code',
        'run_migrations' => 'Run Migrations',
        'update_log' => 'Update Log',
        'how_to_update' => 'How to Update',
        'current_version' => 'Current Version',
        'latest_commit' => 'Latest Commit',
        'check_github' => 'Check GitHub',
        'update_from_github' => 'Update from GitHub',
        'update_database' => 'Update Database',
        'backup_warning' => 'Warning: Please backup your data before updating!',
        'step_1' => 'Check for new updates',
        'step_2' => 'Download new code',
        'step_3' => 'Update database structure',
        'system_update_manager' => 'System Update Manager',
        'could_not_get_version' => 'Could not retrieve version info.',
        'connection_failed' => 'Connection failed.',
        'code_updated_success' => 'Code updated successfully!',
        'failed_pull_updates' => 'Failed to pull updates.',
        'no_migrations_found' => 'No migrations directory found.',
        'migration_running' => 'Running:',
        'migration_completed' => 'completed',
        'migration_failed' => 'failed',
        'update_step_1_desc' => 'See if there are any new commits available on the main branch.',
        'update_step_2_desc' => 'Safely download and merge the latest code changes to your server.',
        'update_step_3_desc' => 'Apply any necessary database changes to keep your system running smoothly.',
        'backup_warning_msg' => 'Please ensure you have a recent backup of your database and files before proceeding with any updates.',
        'git_error_detected' => 'Git configuration not found.',
        'btn_fix_git' => 'Initialize System (Fix Git)',
        'git_fix_success' => 'Git initialized and system linked successfully!',
        'git_fix_failed' => 'Initialization failed.',
        'troubleshooting' => 'Troubleshooting',
        'force_git_init' => 'Force Re-Initialize GitHub Connection',
        'force_git_desc' => 'This process might overwrite local files. Please backup first.',
        'take_backup_now' => 'Go to Backup Page (Recommended)',
        'confirm_git_fix' => 'I understand, proceed with fix',
        'monitor_campaign' => 'Monitor / Manage',
        'no_campaigns_found' => 'No previous campaigns found',
        'status_scheduled' => 'Scheduled',
        'status_running' => 'Running',
        'view_report' => 'View Report',
        'export_csv' => 'Export CSV',
        'id' => 'ID',
        'page' => 'Page',
        'delete_campaign' => 'Delete Campaign',
        'confirm_delete' => 'Are you sure you want to delete this campaign? This cannot be undone.',
        'campaign_deleted' => 'Campaign deleted successfully.',
        'date_created' => 'Date Created',
        'no_leads_selected' => 'No Leads Selected',
        'please_select_leads_first' => 'Please select target leads from the inbox first to start.',
        'go_to_inbox' => 'Go to Inbox',
        'targeting' => 'Targeting',
        'selected_leads_from' => 'Selected <span class="highlight text-indigo-400 font-bold mx-1">%d</span> leads from page <span class="highlight text-white font-bold mx-1">%s</span>',
        'scheduled_at' => 'Scheduled At',
        'run_now' => 'Run Immediately Now',
        'schedule_campaign' => 'Schedule Campaign',
        'start_immediately' => 'Start execution right after saving',
        'go_to_runner' => 'Save & Go to Runner',
        'messenger_preview_hint' => 'This is how your message will look on Messenger.',
        'preview_name_placeholder' => 'John Doe',
        'vars_hint' => 'Available Variables',
        'campaign_name' => 'Campaign Name',
        'message_text' => 'Message Text',
        'image_url' => 'Image URL (Optional)',
        'message_preview' => 'Message Preview',
        'message_placeholder' => 'Hi {{name}}, how can I help you?',
        'image_url_placeholder' => 'https://example.com/image.jpg',
        'online_status' => 'Online',
        'customer_msg_sample' => "Hello! I'm interested in your services.",
        'preview_empty_msg' => '(Type your message to see preview...)',
        'just_now' => 'Just now',
        'chars_unit' => 'chars',
        'campaign_default_name' => 'Campaign',
        'upload_image' => 'Upload Image',
        'use_url' => 'Use URL',
        'local_file' => 'Local File',
        'runner_title' => 'Campaign Runner',
        'ready_msg' => 'Ready to Launch...',
        'queue' => 'Queue',
        'campaign_not_found' => 'Campaign not found.',
        'campaign_label' => 'Campaign:',
        'empty_queue_title' => 'Queue is empty or completed.',
        'empty_queue_desc' => 'Try re-scanning the page if this is unexpected.',
        'checking_token' => 'Checking Access Token...',
        'token_invalid' => 'Token Expired or Invalid',
        'conn_error' => 'Connection error while checking token.',
        'sending_batch' => 'Sending Batch...',
        'waiting' => 'Waiting',
        'confirm_stop_campaign' => 'Stop current operation and go back?',
        'enter_valid_token' => 'Please enter a valid token',
        'updating_btn' => 'Updating...',
        'update_token_error' => 'Error updating token.',
        'campaign_finished_title' => '🎉 Campaign Finished',
        'rerun_campaign' => 'RE-RUN CAMPAIGN',
        'status_sending_small' => 'SENDING',
        'status_sent_small' => 'SENT',
        'status_failed_small' => 'FAILED',
        'status_pending_small' => 'PENDING',
        'service_error' => 'Error connecting to sender service.',
        'export_error' => 'Failed to generate image. Please try a screenshot.',
        'lead_info' => 'Lead Info',
        'queue_list' => 'Queue List',
        'campaign_progress' => 'Campaign Progress',
        'estimated_time' => 'Estimated Time',
        'finished_status' => 'Finished',
        'retry_count_label' => 'Retries',
        'retry_delay_label' => 'Retry Delay (s)',
        'retrying_status' => 'Retrying (%d/%d)',
        'starts_in' => 'Starts in:',


        // Contact
        'contact_us' => 'Contact Us',
        'contact_subtitle' => 'Have a question? Our team is ready to respond as soon as possible.',
        'send_message' => 'Send Message',
        'your_name' => 'Full Name',
        'your_message' => 'Your Message',
        'subject' => 'Subject',
        'phone' => 'Phone Number',
        'msg_success' => 'Your message has been sent successfully! We will get back to you soon.',
        'search_placeholder' => 'Search by name or PSID...',
        'token_expired_title' => 'Session Expired!',
        'token_expired_msg' => 'Sorry, it seems your Access Token has expired. Don\'t worry, you can update it here and continue from where you left off.',
        'new_token_placeholder' => 'Enter new Page Access Token...',
        'update_token_btn' => 'Update & Continue',
        'token_updated_success' => 'Token updated successfully! You can now resume the campaign.',

        // Footer & Misc
        'about_us' => 'About Us',
        'about_subtitle' => 'Your Smart Partner in Digital Marketing',
        'about_desc' => 'We provide the most powerful technical solutions for extracting interested lead data from Facebook. Our goal is to help businesses and marketers reach their target audience with high precision and professionalism, ensuring the highest levels of security and speed.',
        'about_subtitle_ar' => 'About Subtitle (Arabic)',
        'about_subtitle_en' => 'About Subtitle (English)',
        'about_btn_ar' => 'About Button (Arabic)',
        'about_btn_en' => 'About Button (English)',
        'about_btn' => 'About Button',
        'terms_service' => 'Terms of Service',
        'privacy_policy' => 'Privacy Policy',
        'follow_us' => 'Follow Us',
        'hero_badge' => '#1 Marketing Tool',
        'hero_feature' => 'Up to 99% accuracy in extracting genuinely interested leads.',
        'fast_secure' => 'Fast & Secure',
        'happy_users' => '+5000 Marketers',

        // Notifs
        'notifications' => 'Notifications',
        'mark_all_read' => 'Mark All Read',
        'view_all' => 'View All',
        'no_notifications' => 'No notifications',
        'api_status' => 'API Status',
        'connected' => 'Connected',
        'not_connected' => 'Not Connected',
        'manage_profiles' => 'Manage Profiles',
        // Facebook Accounts (User Section)
        'link_new_account' => 'Link New Account',
        'account_name_label' => 'Account Name (for reference)',
        'account_name_placeholder' => 'e.g. My Personal Account',
        'fb_id_label' => 'Facebook ID (Optional)',
        'fb_id_placeholder' => '123456789',
        'access_token_label' => 'Access Token (EAAB...)',
        'access_token_placeholder' => 'Paste your graph API token here...',
        'access_token_note' => 'A valid token is required to fetch pages and content.',
        'btn_link_account' => 'Link Account Now',
        'your_linked_accounts' => 'Your Linked Accounts',
        'btn_sync_pages' => 'Sync Pages',
        'confirm_delete_account' => 'Are you sure? This will remove all associated data.',
        'synced_pages_title' => 'Synced Pages',
        'synced_pages_subtitle' => 'Pages fetched from your accounts. Select a page to view Inbox.',
        'page_info' => 'Page Info',
        'category' => 'Category',
        'no_accounts_linked' => 'No accounts linked yet. Add one to start.',
        'no_pages_synced_desc' => 'No pages synced yet. Click "Sync Pages" on an account above.',
        'msg_account_linked' => 'Account linked successfully!',
        'msg_sync_success' => 'Successfully synced %d pages!',
        'msg_no_pages' => 'No pages found for this account.',
        'no_pages_synced' => 'No Synced Pages',
        'open_inbox' => 'Open Inbox',

        // Support
        'support_tickets' => 'Support Tickets',
        'create_ticket' => 'New Ticket',
        'status' => 'Status',
        'last_update' => 'Last Update',
        'open' => 'Open',
        'closed' => 'Closed',
        'answered' => 'Answered',
        'solved' => 'Solved',
        'arabic' => 'Arabic',
        'english' => 'English',

        // Misc
        'notifications_muted_msg' => 'Notifications muted',
        'unmute_notifications' => 'Unmute Notifications',
        'mute_notifications' => 'Mute Notifications',
        'mark_read' => 'Mark as Read',
        'view_all_notifications' => 'View All Notifications',
        'features' => 'Features',
        'faqs' => 'FAQs',
        'testimonials' => 'Testimonials',
        'contact' => 'Contact',
        'how_it_works' => 'How it Works',
        'backup_restore' => 'Backup & Restore',
        'close_menu' => 'Close Menu',
        'stat_users' => 'Active Users',
        'stat_leads' => 'Leads Extracted',
        'stat_satisfaction' => 'Satisfaction',
        'stat_support' => '24/7 Support',
        'cta_title' => 'Ready to grow your business?',
        'cta_subtitle' => 'Start extracting leads today and leave your competitors behind.',
        'cta_button' => 'Create Free Account',
        'sim_title' => 'Profit Simulator',
        'sim_desc' => 'Estimate your marketing ROI',
        'sim_followers' => 'Target Followers',
        'sim_engagement' => 'Expected Engagement',
        'sim_total_leads' => 'Total Targeted Leads',
        'sim_accuracy' => 'High extraction accuracy',
        'sim_btn' => 'Start Extracting Now',
        'settings_updated' => 'Settings updated successfully!',
        'site_info' => 'Site Info',
        'hero_section' => 'Hero Section',
        'about_section' => 'About Section',
        'contact_info_settings' => 'Contact Settings',
        'smtp_settings' => 'SMTP Settings',
        'notification_settings' => 'Notification Settings',
        'site_logo' => 'Site Logo',
        'site_favicon' => 'Site Favicon',
        'site_name_ar' => 'Site Name (Arabic)',
        'site_name_en' => 'Site Name (English)',
        'footer_description_ar' => 'Footer Description (Arabic)',
        'footer_description_en' => 'Footer Description (English)',
        'contact_form_email' => 'Contact Form Email',
        'maintenance_mode' => 'Maintenance Mode',
        'off_live' => 'Off (Live)',
        'on_maintenance' => 'On (Maintenance)',
        'enable_scroll_top' => 'Enable Scroll Top',
        'hero_title_ar' => 'Hero Title (Arabic)',
        'hero_feature_ar' => 'Hero Feature (Arabic)',
        'hero_subtitle_ar' => 'Hero Subtitle (Arabic)',
        'hero_title_en' => 'Hero Title (English)',
        'hero_feature_en' => 'Hero Feature (English)',
        'hero_subtitle_en' => 'Hero Subtitle (English)',
        'about_title_ar' => 'About Title (Arabic)',
        'about_desc_ar' => 'About Description (Arabic)',
        'mission_ar' => 'Mission (Arabic)',
        'vision_ar' => 'Vision (Arabic)',
        'about_title_en' => 'About Title (English)',
        'about_desc_en' => 'About Description (English)',
        'mission_en' => 'Mission (English)',
        'vision_en' => 'Vision (English)',
        'social_links' => 'Social Media Links',
        'smtp_configuration' => 'SMTP Configuration',
        'smtp_host' => 'SMTP Host',
        'smtp_port' => 'SMTP Port',
        'smtp_encryption' => 'Encryption',
        'smtp_username' => 'SMTP Username',
        'smtp_password' => 'SMTP Password',
        'smtp_from_name' => 'Sender Name',
        'smtp_info_note' => 'Ensure SMTP settings are correct for email notifications to function.',
        'email_notifications_control' => 'Email Notifications Control',
        'registration_events' => 'Registration Events',
        'notify_admin_new_user' => 'Notify Admin on New Registration',
        'notify_admin_new_user_desc' => 'Send email to admin when a new user joins.',
        'notify_client_welcome' => 'Send Welcome Email to User',
        'notify_client_welcome_desc' => 'Send a welcome message to user after registration.',
        'exchange_events' => 'Order Events',
        'notify_admin_new_order' => 'Notify Admin on New Extraction',
        'notify_admin_new_order_desc' => 'Notify admin when a new extraction starts.',
        'notify_client_new_order' => 'Notify User on Extraction Start',
        'notify_client_new_order_desc' => 'Send confirmation to user when extraction begins.',
        'notify_client_status_change' => 'Notify on Status Change',
        'notify_client_status_change_desc' => 'Notify user when extraction task completes or fails.',
        'security_note' => 'Security Note',
        'forgot_password_always_active' => 'Password recovery is always active and unaffected by these settings.',
        'maintenance_placeholder' => 'The site is currently under maintenance, we will be back soon...',
        'landing_content' => 'Landing Content',
        'features_section' => 'Features Section',
        'steps_section' => 'Steps Section',
        'stats_section' => 'Stats Section',
        'cta_section' => 'CTA Section',
        'about_image' => 'About Us Image',
        'stat_value' => 'Numeric Value',
        'feature' => 'Feature',
        'step' => 'Step',
        'icon' => 'Icon',
        'choose_icon' => 'Choose Icon',
        'features_title_ar' => 'Features Title (Arabic)',
        'features_title_en' => 'Features Title (English)',
        'how_it_works_title_ar' => 'Steps Title (Arabic)',
        'how_it_works_title_en' => 'Steps Title (English)',
        'testimonials_title_ar' => 'Testimonials Title (Arabic)',
        'testimonials_title_en' => 'Testimonials Title (English)',
        'faqs_title_ar' => 'FAQs Title (Arabic)',
        'faqs_title_en' => 'FAQs Title (English)',
        'facebook' => 'Facebook',
        'twitter' => 'Twitter (X)',
        'instagram' => 'Instagram',
        'telegram' => 'Telegram',
        'whatsapp' => 'WhatsApp',
        'youtube' => 'YouTube',
        'linkedin' => 'LinkedIn',
        'tiktok' => 'TikTok',
        'contact_phone' => 'Contact Phone',
        'contact_address_ar' => 'Address (Arabic)',
        'contact_address_en' => 'Address (English)',
        'services_section' => 'Our Services Section',
        'services_title_ar' => 'Services Title (Arabic)',
        'services_title_en' => 'Services Title (English)',
        'service' => 'Service',
        'service_title' => 'Service Title',
        'service_desc' => 'Service Description (One point per line)',
        'service_btn_ar' => 'Service Button (Arabic)',
        'service_btn_en' => 'Service Button (English)',
        'most_popular' => 'Most Popular',
        'featured_service' => 'Featured Service',
        'testimonial' => 'Testimonial',
        'testimonial_content' => 'Testimonial Content',
        'testimonial_author' => 'Author Name',
        'testimonial_image' => 'Customer Image',
        'faq' => 'FAQ Item',
        'faq_question' => 'Question',
        'faq_answer' => 'Answer',
        'contact_info' => 'Contact Info',
        'contact_email' => 'Contact Email',
        'test_smtp_settings' => 'Test SMTP Settings',
        'test_email_address' => 'Test Email Address',
        'send_test_email' => 'Send Test Email',
        'smtp_test_success' => 'Test email sent successfully! Please check your inbox.',
        'smtp_test_failed' => 'Failed to send test email. Please check configuration.',
        'msg_account_deleted' => 'Account deleted successfully',
        'msg_rate_limit_error' => 'Sorry, the application request limit has been reached temporarily. Please wait a few minutes and try again.',
        'fb_accounts_desc' => 'Manage and control Facebook accounts and permissions',

        // Inbox Page
        'inbox_page_title' => 'Page Inbox',
        'page_id_label' => 'Page ID:',
        'last_updated' => 'Last Updated:',
        'never_updated' => 'Never',
        'total_audience' => 'Total Audience',
        'scan_inbox' => 'Scan Inbox',
        'scan_limit' => 'Scan Limit',
        'chats_label' => 'chats',
        'clear_database' => 'Clear Database',
        'clear_confirm' => 'Are you sure you want to clear all leads from the database?',
        'inbox_leads' => 'Inbox Leads',
        'create_campaign' => 'Create Campaign',
        'user_identity' => 'User Identity',
        'psid_label' => 'PSID (Private ID)',
        'interaction_date' => 'Interaction',
        'fb_user_role' => 'Facebook User',
        'no_leads_found' => 'No leads found yet',
        'click_scan_hint' => 'Click "Scan Inbox" to fetch recent conversations.',
        'scan_success' => 'Scanned inbox successfully! Processed %d conversations.',
        'scan_no_results' => 'No conversations found in recent inbox.',
        'leads_cleared' => 'Leads cleared successfully.',
        'page_not_found' => 'Page not found or access denied.',
        'scan_delay_label' => 'Delay (Seconds)',
        'scan_delay_hint' => 'Wait between requests to avoid bans',
        'extract_mode_label' => 'Extraction Mode',
        'extract_all_option' => 'Extract All',
        'extract_limit_option' => 'Specific Limit',
        'btn_start' => 'Start Campaign',
        'btn_pause' => 'Pause',
        'btn_resume' => 'Resume',
        'btn_stop' => 'Stop',
        'status_ready' => 'Ready to start...',
        'status_scanning' => 'Scanning... (%s items)',
        'status_paused' => 'Paused',
        'status_finished' => 'Scan Complete!',
        'lbl_delay' => 'Delay',
        'lbl_limit' => 'Limit',
        'lbl_batch_size' => 'Batch Size',
        'lbl_total_goal' => 'Total Goal',
        'status_processed' => 'Processed %s leads...',
        'status_sleeping' => 'Waiting %s seconds...',
        'lbl_seconds' => 's',
        'report_title' => 'Campaign Summary Report',
        'report_success' => 'Success Sent',
        'report_failed' => 'Failed Delivery',
        'report_delivered' => 'DELIVERED SUCCESSFULLY',
        'report_needs_re_routing' => 'NEEDS RE-ROUTING',
        'report_total_recipients' => 'Total Recipients',
        'report_date_logged' => 'Date Logged',
        'report_powered_by' => 'POWERED BY MARKETATION ENGINE',
        'report_save_image' => 'SAVE AS IMAGE (.PNG)',
        'report_close' => 'CLOSE REPORT',
        'report_people' => 'People',
        'generating_image' => 'GENERATING IMAGE...',
        'save_failed' => 'Save Failed',
        'save_failed_network' => 'Network Error',
        'batch_size' => 'Batch Size (Msg)',
        'unit_s' => 's',
        'unit_msg' => 'msg',
        'lbl_retry_delay' => 'Retry Delay',
        'lbl_retry_count' => 'Retry Count',
        'cron_manager_title' => 'Auto Task Manager',
        'auto_cron_title' => 'Self-Running Mode (Hands-Free)',
        'auto_cron_desc' => 'When enabled, the system will keep triggering itself in the background even if you close the site. This uses a Self-Looping technique to ensure campaign continuity.',
        'start_auto_loop' => 'Enable Auto-Loop',
        'stop_auto_loop' => 'Disable Auto-Loop',
        'loop_enabled' => 'Auto-Loop Enabled. Campaigns will run in background.',
        'loop_disabled' => 'Auto-Loop Disabled.',
        'system_running_background' => 'System is running in background...',
        'manual_cron_title' => 'Manual Cron Job Setup (cPanel)',
        'manual_cron_desc' => 'Prefer manual setup? Copy this command to your hosting cPanel to run every minute:',
        'click_to_copy' => 'Click to Copy',
    ],
];

// --- Notification Functions ---

function addNotification($user_id, $title, $message, $link = '#')
{
    $pdo = getDB();
    $stmt = $pdo->prepare("INSERT INTO notifications (user_id, title, message, link) VALUES (?, ?, ?, ?)");
    return $stmt->execute([$user_id, $title, $message, $link]);
}

function getUnreadNotifications($user_id, $limit = 5)
{
    $pdo = getDB();
    $stmt = $pdo->prepare("SELECT * FROM notifications WHERE user_id = ? AND is_read = 0 ORDER BY created_at DESC LIMIT ?");
    $stmt->bindParam(1, $user_id, PDO::PARAM_INT);
    $stmt->bindParam(2, $limit, PDO::PARAM_INT);
    $stmt->execute();
    return $stmt->fetchAll(PDO::FETCH_ASSOC);
}

function getUnreadCount($user_id)
{
    $pdo = getDB();
    if (!$pdo)
        return 0;

    // Check if user is muted logic - Hide badge if muted
    $stmt = $pdo->prepare("SELECT preferences FROM users WHERE id = ?");
    $stmt->execute([$user_id]);
    $prefs = json_decode($stmt->fetchColumn() ?: '{}', true);

    // If muted, return 0 (hide badge)
    if (!empty($prefs['notifications_muted'])) {
        return 0;
    }

    $stmt = $pdo->prepare("SELECT COUNT(*) FROM notifications WHERE user_id = ? AND is_read = 0");
    $stmt->execute([$user_id]);
    return $stmt->fetchColumn();
}

function getAdminTicketUnreadCount()
{
    $pdo = getDB();
    $stmt = $pdo->query("SELECT COUNT(*) FROM support_tickets WHERE is_read_admin = 0");
    return (int) $stmt->fetchColumn();
}

function getUserTicketUnreadCount($user_id)
{
    $pdo = getDB();
    $stmt = $pdo->prepare("SELECT COUNT(*) FROM support_tickets WHERE user_id = ? AND is_read_user = 0");
    $stmt->execute([$user_id]);
    return (int) $stmt->fetchColumn();
}

/* Exchange functions mocked to prevent crashes if called */
function getAdminExchangeUnreadCount()
{
    return 0;
}
function markExchangeAsRead($id)
{
    return true;
}

function markNotificationAsRead($notification_id, $user_id)
{
    $pdo = getDB();
    $stmt = $pdo->prepare("UPDATE notifications SET is_read = 1 WHERE id = ? AND user_id = ?");
    return $stmt->execute([$notification_id, $user_id]);
}

function notifyAdmins($title, $message, $link = '#')
{
    $pdo = getDB();
    // Fetch all admins
    $stmt = $pdo->query("SELECT id FROM users WHERE role = 'admin'");
    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
        addNotification($row['id'], $title, $message, $link);
    }
}


function getSetting($key, $default = null)
{
    static $settings = null;
    if ($settings === null) {
        $settings = [];
        $pdo = getDB();
        if ($pdo) {
            $stmt = $pdo->query("SELECT setting_key, setting_value FROM settings");
            if ($stmt) {
                while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
                    $settings[$row['setting_key']] = $row['setting_value'];
                }
            }
        }
    }
    return isset($settings[$key]) ? $settings[$key] : $default;
}

function __($key, $force_lang = null)
{
    global $translations, $lang;

    $current_lang = $force_lang ?? $lang;

    // Check if there's a dynamic setting for this key + current lang
    $dynamicKey = $key . '_' . $current_lang;
    $settingValue = getSetting($dynamicKey);
    if ($settingValue)
        return $settingValue;

    // Special case for site_name
    if ($key === 'site_name') {
        $settingValue = getSetting('site_name_' . $current_lang);
        if ($settingValue)
            return $settingValue;
    }

    return isset($translations[$current_lang][$key]) ? $translations[$current_lang][$key] : $key;
}

// Database Connection Helper
function getDB()
{
    global $pdo;
    if (isset($pdo)) {
        return $pdo;
    }
    if (file_exists(__DIR__ . '/db_config.php')) {
        require_once __DIR__ . '/db_config.php';
        return $pdo;
    }
    return null;
}

function isLoggedIn()
{
    return isset($_SESSION['user_id']);
}

function isAdmin()
{
    return isset($_SESSION['role']) && $_SESSION['role'] === 'admin';
}
?>